version: "3"

services:
    streamlit-app:
        build: .
        ports:
            - "8501:8501"
        volumes:
            - ./models:/app/models # Montar o diretório de modelos
        environment:
            - PYTHONUNBUFFERED=1
